# -*- coding: utf-8 -*-
"""drama_recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Qa2IO5x988Nf4cEISYH2Uq9zqrv4VK7
"""

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from difflib import get_close_matches

df = pd.read_csv("mydramalist.csv")

df.columns

df = df.drop(['Unnamed: 0','no_of_reviews', 'no_of_viewers',
        'aka_names', 'screenwriter', 'type_of_show', 'episodes',
        'end_date', 'start_date','duration', 'no_of_rating',
        'content_rating', 'where_to_watch','no_of_extracted_reviews',
        'Total_sentences', 'popularity', 'support_role',
       'POSITIVE_people_sentiment', 'POSITIVE_sentences',
       'NEGATIVE_people_sentiment', 'NEGATIVE_sentences',
       'reviewer_location_info', 'reviewer_gender_info'
              ],axis=1)

df.head()

comma_cols = ["director", "genres", "tags", "country", "main_role"]

for col in comma_cols:
    df[col] = df[col].fillna("").apply(lambda x: [i.strip() for i in x.split(",") if i.strip()])

df.rename(columns={"name":"title","content":"synopsis","tags":"dramatags"},inplace=True)

df['synopsis'] = df['synopsis'].fillna('').apply(lambda x: x.split())

df.isnull().sum()

df.dropna(inplace=True)

df['year'] = df['year'].apply( lambda x:[str(x)])
df['rank'] = df['rank'].apply( lambda x:int(x))

df.head(2)

df['tags'] = (df['synopsis']*2 + df['year'] + df['director'] + df['genres']*2
              + df['country'] + df["dramatags"] + df["main_role"])

drama = df[['rank','title','tags']]

drama.head(2)

drama['tags'] = drama['tags'].apply(lambda x: " ".join(x))

drama['tags'] = drama['tags'].apply(lambda x: x.lower())

tfidf = TfidfVectorizer(max_features=5000, stop_words='english')
vectors = tfidf.fit_transform(drama['tags']).toarray()

similarity = cosine_similarity(vectors)

def recommend(movie, min_rating=0, genre=None, n=5):
    movie_list = drama['title'].tolist() # Refers to the global 'drama' DataFrame

    match = get_close_matches(movie, movie_list, n=1, cutoff=0.5)
    if not match:
        return []

    movie_name = match[0]
    # Get index from the 'drama' DataFrame for consistency with 'similarity' array which is based on 'drama'
    idx = drama[drama['title'] == movie_name].index[0]

    sim_scores = list(enumerate(similarity[idx]))

    filtered = []
    for i_idx, score in sim_scores: # Renamed i to i_idx for clarity
        # Retrieve the full row from the original 'df' using the index 'i_idx'
        # Renamed the local variable to avoid shadowing global 'drama'
        current_full_movie_details = df.iloc[i_idx]

        # Rating filter
        # Use the true 'rating' score (0-10) instead of rank
        if current_full_movie_details['rating'] < min_rating:
            continue

        # Genre filter
        # 'genres' is a list in df, need to join to string for 'in' operator
        if genre and genre.lower() not in " ".join(current_full_movie_details['genres']).lower():
            continue

        filtered.append((i_idx, score)) # Append the index from df and the score

    filtered = sorted(filtered, key=lambda x: x[1], reverse=True)[1:n+1]

    results = []
    for i_idx, _ in filtered: # Unpack index and score
        d = df.iloc[i_idx] # Get full details for output from original df
        results.append({
            "title": d['title'],       # Use 'title' as renamed
            "rating": d.get('rating', 'N/A'),
            "genres": " ".join(d.get('genres', [])), # Join genres list into a string
            "description": " ".join(d.get('synopsis', [])) # Join synopsis list into a string
        })

    return results

